# PostgreSQL. Version ?
development:
  adapter: postgresql
  encoding: unicode
  database: deeddone-backend-development
  pool: 5

test: &test
  adapter: postgresql
  encoding: unicode
  database: deeddone-backend-test
  pool: 5

dev_integration:
  adapter: postgresql
  encoding: unicode
  database: deeddone-backend-integration
